name: Deploy master branch

on:
  push:
    branches: [ master ]

jobs:
  update-servers:
    name: "${{ matrix.server }}.ta-7.ru update"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        server:
          - 09vk
          - alekseeva
          - alkomed
          - aplus
          - a-rosa
          - atp
          - avtodoctor69
          - avtomedik
          - avto-med
          - cert
          - chinara
          - dopusk
          - leskraft
          - medi-t
          - meduslugi
          - medzenklinik
          - mkyyzch
          - mt
          - oreltaxi
          - pomosh
          - p-osmotr
          - profmed
          - puti-nn
          - smirnova
          - soyuzmed
          - tomilko
          - tverkooptrans
    steps:
    - name: Update domains
      uses: appleboy/ssh-action@master
      env:
        GITHUB_SHA: ${{ github.sha }}
        PROJECT_PATH: /home/admin/web/${{ matrix.server }}.ta-7.ru/public_html
      with:
        host: 213.139.210.53
        username: root
        key: ${{ secrets.CLIENTS_SSHKEY }}
        port: 22
        envs: PROJECT_PATH,GITHUB_SHA
        script: |
            ${PROJECT_PATH}/.scripts/deploy-master.sh
