name: Deploy master branch

on:
  push:
    branches: [ master ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile CSS and Javascript
        run: |
          npm install --force
          npm run production
      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf public-"${GITHUB_SHA}".tar.gz public/css public/js public/mix-manifest.json
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: front-build
          path: public-${{ github.sha }}.tar.gz
  upload-deployment-artifacts:
    name: Upload artifacts
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: front-build
      - name: Upload artifacts
        uses: appleboy/scp-action@master
        with:
          host: 213.139.210.53
          username: root
          key: ${{ secrets.CLIENTS_SSHKEY }}
          port: 22
          source: public-${{ github.sha }}.tar.gz
          target: /home/admin/web/artifacts
  update-servers:
    name: "${{ matrix.server }}.ta-7.ru update"
    runs-on: ubuntu-latest
    needs: upload-deployment-artifacts
    strategy:
      max-parallel: 1
      matrix:
        server:
          - 09vk
          - alekseeva
          - alkomed
          - aplus
          - a-rosa
          - atp
          - avtodoctor69
          - avtomedik
          - avto-med
          - cert
          - chinara
          - demo
          - dopusk
          - leskraft
          - medi-t
          - meduslugi
          - medzenklinik
          - mkyyzch
          - mt
          - oreltaxi
          - pomosh
          - p-osmotr
          - profmed
          - puti-nn
          - smirnova
          - soyuzmed
          - tomilko
          - tverkooptrans
    steps:
    - name: Update domains
      uses: appleboy/ssh-action@master
      env:
        GITHUB_SHA: ${{ github.sha }}
        PROJECT_PATH: /home/admin/web/${{ matrix.server }}.ta-7.ru/public_html
      with:
        host: 213.139.210.53
        username: root
        key: ${{ secrets.CLIENTS_SSHKEY }}
        port: 22
        envs: PROJECT_PATH,GITHUB_SHA
        script: |
            ${PROJECT_PATH}/.scripts/deploy-master.sh
